spring.application.name=marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=postgres
spring.datasource.password=Ayush08@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=secured-secret-key-for-json-web-token-generation-used-in securing-marketplace-application
jwt.expiration=900000

cloudinary.cloud-name=dy8e5wijp
cloudinary.api-key=199539427372751
cloudinary.api-secret=7ZfUcEzO5DlWXJ2E9f-Wjtnitqg
